name: TuxMemory release APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  apk:
    name: Generate release builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Decode keystore and create jks
        run: echo "${{ secrets.KEYSTORE_JKS_BASE64 }}" | base64 --decode > keystore.jks

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build release APK
        run: bash ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Rename APK 
        run:
          mv "./app/build/outputs/apk/release/Tux Memory-release.apk" "./app/build/outputs/apk/release/TuxMemory.apk"

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: Tux Memory
          path: app/build/outputs/apk/release/TuxMemory.apk

          
