name: TuxMemory release APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  apk:
    name: Generate release builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'
        

      - name: Generate keystore.properties
        run: |
          cat <<EOF > keystore.properties
          storePassword:${{ secrets.KEYSTORE_STORE_PASSWORD }}
          keyPassword:${{ secrets.KEYSTORE_KEY_PASSWORD }}
          keyAlias:${{ secrets.KEYSTORE_KEY_ALIAS }}
          storeFile:${{ vars.KEYSTORE_STORE_FILE_PATH }}
          EOF

      - name: Decode keystore and create jks
        run: echo "${{ secrets.KEYSTORE_JKS_BASE64 }}" | base64 --decode > keystore.jks

      - name: Build release APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Rename APK 
        run:
          mv "./app/build/outputs/apk/release/app-release.apk" "./app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}.apk"

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}.apk

          
